name: pyboost11_test

on:
  push:
  pull_request:
  schedule:
    - cron: '34 16 * * *'

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
        matrix:
          os: [ubuntu-20.04, macos-latest]
          cmake_build_type: [Release]

        fail-fast: false

    steps:

    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: dependency (ubuntu)
      if: matrix.os != 'macos-latest'
      run: |
        sudo apt-get -qqy update
        sudo apt-get -qy install \
            sudo curl git build-essential make cmake libc6-dev gcc-9 g++-9 \
            python3 python3-dev python3-venv \
            libboost-dev libboost-python-dev
        sudo pip3 install setuptools
        sudo pip3 install numpy pytest flake8
        echo "libboost_python:"
        echo "  ls libboost_python*:"
        ls -al /usr/lib/x86_64-linux-gnu/libboost_python*

    - name: dependency (macos)
      if: matrix.os == 'macos-latest'
      run: |
        brew install python3 llvm boost boost-python3
        ln -s "$(brew --prefix llvm)/bin/clang-format" "/usr/local/bin/clang-format"
        ln -s "$(brew --prefix llvm)/bin/clang-tidy" "/usr/local/bin/clang-tidy"
        pip3 install -U setuptools
        pip3 install -U numpy pytest flake8

    - name: dependency (manual)
      run: sudo ${GITHUB_WORKSPACE}/contrib/dependency/install.sh pybind11

    - name: show dependency
      run: |
        echo "gcc path: $(which gcc)"
        echo "gcc version: $(gcc --version)"
        echo "cmake path: $(which cmake)"
        echo "cmake version: $(cmake --version)"
        echo "python3 path: $(which python3)"
        echo "python3 version: $(python3 --version)"
        echo "pip3 path: $(which pip3)"
        python3 -c 'import numpy ; print("numpy.__version__:", numpy.__version__)'
        echo "pytest path: $(which pytest)"
        echo "pytest version: $(pytest --version)"
        echo "flake8 path: $(which flake8)"
        echo "flake8 version: $(flake8 --version)"

    - name: pytest
      run: |
        make -C code test VERBOSE=1
